import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect, useRef } from "react";

// Components
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Link from "next/link";
import Featwork from "@/components/Featwork";
import BigText from "@/components/BigText";
import ExploreWork from "@/components/ExploreWork";
import OtherServ from "@/components/OtherServ";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const scrollRef = useRef(null);

  const [heroScroll, setHeroScroll] = useState(false);
  const [bigScroll, setBigScroll] = useState(false);

  let firstY = 2.2;
  let firstYPillow = 1.95;
  let secondY = 3.13;
  let thirdY = 4;

  function handleScroll(e) {
    let windLoc = window.scrollY / window.innerHeight;
    console.log(window.scrollY / window.innerHeight);
    if (windLoc >= firstY) {
      if (windLoc >= firstY && windLoc < secondY) {
        setBigScroll(true);
        setHeroScroll(true);
      } else {
        return;
      }
    } else if (windLoc >= 0.4 && windLoc < firstY) {
      setHeroScroll(true);
    } else if (windLoc < 0.4) {
      setHeroScroll(false);
      setBigScroll(false);
    } else {
      return;
    }
  }

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
  }, []);
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main ref={scrollRef} className={`${styles.main} ${inter.className}`}>
        <Hero heroScroll={heroScroll} bigScroll={bigScroll} />
        <BigText />
        <ExploreWork />
        <OtherServ />
      </main>
    </>
  );
}
